{
 "title": "Codefresh argo-cd events reporter (v2)",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "runtime",
    "label": "Runtime",
    "query": {
     "query": "label_values(codefresh_event_reporter_queue_size,namespace)"
    }
   },
   {
    "name": "reporter_shard",
    "label": "Shard Number",
    "query": {
     "query": "label_values(codefresh_event_reporter_queue_size,reporter_shard)"
    }
   },
   { "name": "group_by", "label": "Group By", "query": "reporter_shard, application" },
   { "name": "resolution", "query": "30s, 1m, 5m, 10m, 30m, 1h" }
  ]
 },
 "panels": [
  { "title": "General stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Queue size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n    codefresh_event_reporter_queue_size\n    {reporter_shard=~\"$reporter_shard\", namespace=~\"$runtime\"}\n) by(reporter_shard)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Events enqueued",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "sum(\n    rate(\n        codefresh_event_reporter_enqueued_events_total\n        {reporter_shard=~\"$reporter_shard\", namespace=\"$runtime\"}\n    [$__rate_interval])\n) by(${group_by:csv})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Events stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Average processing time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(\n    rate(\n        codefresh_event_reporter_event_processing_duration_sum\n        {reporter_shard=~\"$reporter_shard\", namespace=~\"$runtime\"}\n        [$__rate_interval])\n) by(${group_by:csv})\n/\nsum(\n    rate(\n        codefresh_event_reporter_event_processing_duration_count\n        {reporter_shard=~\"$reporter_shard\", namespace=~\"$runtime\"}\n    [$__rate_interval])\n) by(${group_by:csv})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dropped events",
   "type": "timeseries",
   "description": "Dropped due to one of:\n- rate limited\n- queue overflow",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "sum (\n    rate(\n        codefresh_event_reporter_dropped_events_total\n        {reporter_shard=~\"$reporter_shard\", namespace=~\"$runtime\"}\n    [$__rate_interval])\n) by(${group_by:csv})\n> 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errored events",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "sum (\n    rate(\n        codefresh_event_reporter_errored_events_total\n        {reporter_shard=~\"$reporter_shard\", namespace=~\"$runtime\"}\n    [$__rate_interval])\n) by(${group_by:csv})\n> 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Processing performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "App event performance",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 47 },
     "targets": [
      {
       "expr": "sum(\n    rate(\n        codefresh_event_reporter_event_processing_duration_bucket\n        {reporter_shard=~\"$reporter_shard\", namespace=~\"$runtime\"}\n    [$__rate_interval])\n) by(le) ",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Go stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Used",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(\n    go_memstats_heap_alloc_bytes\n    {namespace=~\"$runtime\", pod=~\"argo-cd-event-reporter-$reporter_shard.+\"}\n) by(pod)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Number of go routines",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(\n    go_goroutines\n    {namespace=~\"$runtime\", pod=~\"argo-cd-event-reporter-$reporter_shard.+\"}\n) by(pod)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Number of OS threads created",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(\n    go_threads\n    {namespace=~\"$runtime\", pod=~\"argo-cd-event-reporter-$reporter_shard.+\"}\n) by(pod)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}