updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 20
    ignore:
    - dependency-name: k8s.io/*
    groups:
      aws-sdk-v2:
        patterns:
          - "github.com/aws/aws-sdk-go-v2*"
      otel:
        patterns:
          - "go.opentelemetry.io/*"
      golang-x:
        patterns:
          - "golang.org/x/*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      codeql:
        patterns:
          - "github/codeql-action*"

  - package-ecosystem: "npm"
    directory: "/ui/"
    schedule:
      interval: "daily"
