version: "2"
linters:
  enable:
    - errorlint
    - gocritic
    - misspell
    - perfsprint
    - testifylint
    - thelper
    - unparam
    - usestdlibvars
    - whitespace
  settings:
    gocritic:
      disabled-checks:
        - appendAssign
        - assignOp
        - badCond
        - commentFormatting
        - exitAfterDefer
        - ifElseChain
        - mapKey
        - singleCaseSwitch
        - typeSwitchVar
    perfsprint:
      int-conversion: true
      err-error: false
      errorf: false
      sprintf1: true
      strconcat: false
    testifylint:
      enable-all: true
      disable:
        - go-require
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - unparam
        path: (.+)_test\.go
      - path: (.+)\.go$
        text: SA5011
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofumpt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/argoproj/argo-cd/v2
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
