FROM node:25.9.0@sha256:b3aabebc52be68c75504ed9c35bc3df0c74d8f10c66aa27507d2494d6fbff160

WORKDIR /app/ui

COPY ui /app/ui

RUN npm install -g corepack@0.34.6 && corepack enable && pnpm install --frozen-lockfile

ENTRYPOINT ["pnpm", "start"]

