FROM golang:1.9.2

WORKDIR /tmp

RUN curl -O https://get.docker.com/builds/Linux/x86_64/docker-1.13.1.tgz && \
  tar -xzf docker-1.13.1.tgz && \
  mv docker/docker /usr/local/bin/docker && \
  rm -rf ./docker && \
  go get -u github.com/golang/dep/cmd/dep && \
  go get -u gopkg.in/alecthomas/gometalinter.v2 && \
  gometalinter.v2 --install

# Install ksonnet
env KSONNET_VERSION=0.10.0-alpha.2
RUN wget https://github.com/ksonnet/ksonnet/releases/download/v${KSONNET_VERSION}/ks_${KSONNET_VERSION}_linux_amd64.tar.gz && \
    tar -C /tmp/ -xf ks_${KSONNET_VERSION}_linux_amd64.tar.gz && \
    mv /tmp/ks_${KSONNET_VERSION}_linux_amd64/ks /usr/local/bin/ks && \
    rm -rf /tmp/ks_${KSONNET_VERSION}
