FROM node:26.3.1@sha256:3328255b7fe75ceaa7eda906c73ce9edde8fb08fe53c70b696fc143908318153

WORKDIR /app/ui

COPY ui /app/ui

RUN npm install -g corepack@0.34.6 && corepack enable && pnpm install --frozen-lockfile

ENTRYPOINT ["pnpm", "start"]

