apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    app.kubernetes.io/name: argocd-clusterprofile-controller
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/component: clusterprofile-controller
  name: argocd-clusterprofile-controller-network-policy
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: argocd-clusterprofile-controller
  ingress:
    - from:
        - namespaceSelector: { }
      ports:
        - protocol: TCP
          port: 8080
  policyTypes:
  - Ingress
