// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta1 "github.com/argoproj/argo-cd/v3/pkg/apis/application/v1beta1"
	applicationv1beta1 "github.com/argoproj/argo-cd/v3/pkg/client/clientset/versioned/typed/application/v1beta1"
	gentype "k8s.io/client-go/gentype"
)

// fakeApplications implements ApplicationInterface
type fakeApplications struct {
	*gentype.FakeClientWithList[*v1beta1.Application, *v1beta1.ApplicationList]
	Fake *FakeArgoprojV1beta1
}

func newFakeApplications(fake *FakeArgoprojV1beta1, namespace string) applicationv1beta1.ApplicationInterface {
	return &fakeApplications{
		gentype.NewFakeClientWithList[*v1beta1.Application, *v1beta1.ApplicationList](
			fake.Fake,
			namespace,
			v1beta1.SchemeGroupVersion.WithResource("applications"),
			v1beta1.SchemeGroupVersion.WithKind("Application"),
			func() *v1beta1.Application { return &v1beta1.Application{} },
			func() *v1beta1.ApplicationList { return &v1beta1.ApplicationList{} },
			func(dst, src *v1beta1.ApplicationList) { dst.ListMeta = src.ListMeta },
			func(list *v1beta1.ApplicationList) []*v1beta1.Application { return gentype.ToPointerSlice(list.Items) },
			func(list *v1beta1.ApplicationList, items []*v1beta1.Application) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
