FROM golang:1.12.6 as builder

RUN apt-get update && apt-get install -y zip sudo
ADD install.sh .
ADD installers installers

# `make manifests`
RUN ./install.sh kustomize-linux
RUN ./install.sh helm-linux

# `make codegen`
RUN ./install.sh swagger-linux
RUN ./install.sh protoc-linux
RUN ./install.sh jq-linux
RUN ./install.sh codegen-tools

RUN mkdir -p /go/pkg && \
    chmod 777 /go/pkg

# clean-up
RUN apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
