FROM golang:1.12.6 as builder

RUN apt-get update && apt-get install -y zip

ADD install.sh .
ADD installers installers

RUN ./install.sh codegen-tools
RUN ./install.sh codegen-go-tools

RUN mkdir -p /home/user && chmod 777 /home/user
RUN HELM_HOME=/home/user/.helm helm init --client-only

RUN mkdir -p /go/pkg && chmod 777 /go/pkg

RUN apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
