build: helm kustomize test-dummy

.PHONY: helm
helm:
	go build -o bin/helm ./helm

.PHONY: kustomize
kustomize:
	go build -o bin/kustomize ./kustomize

.PHONY: test-dummy
test-dummy:
	go build -o bin/test-dummy ./test-dummy
