{
 "title": "ArgoCD",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "content": "![argoimage](https://avatars1.githubusercontent.com/u/30269780?s=200&v=4)   "
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 2, "y": 0 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - max(process_start_time_seconds{job=\"argocd-server-metrics\"})"
    }
   ]
  },
  {
   "title": "Applications Deployed",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(argocd_app_info)" }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 22, "x": 0, "y": 6 }, "content": "## Application Health:" },
  {
   "title": "Healthy",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (argocd_app_health_status { health_status=\"Healthy\"} == 1)\n"
    }
   ]
  },
  {
   "title": "Progressing",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (argocd_app_health_status { health_status=\"Progressing\" } == 1)"
    }
   ]
  },
  {
   "title": "Missing",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (argocd_app_health_status { health_status=\"Missing\" } == 1)"
    }
   ]
  },
  {
   "title": "Degraded",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (argocd_app_health_status { health_status=\"Degraded\"} == 1)"
    }
   ]
  },
  {
   "title": "Suspended",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (argocd_app_health_status { health_status=\"Suspended\"} == 1)"
    }
   ]
  },
  {
   "title": "Unknown",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (argocd_app_health_status { health_status=\"Unknown\"} == 1)"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 22, "x": 0, "y": 13 }, "content": "## Application Sync Status:" },
  {
   "title": "Synced",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum( argocd_app_sync_status {sync_status = \"Synced\"} == 1)"
    }
   ]
  },
  {
   "title": "OutOfSync",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 10, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum( argocd_app_sync_status {sync_status = \"OutOfSync\"} == 1)"
    }
   ]
  },
  {
   "title": "Unknown",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum( argocd_app_sync_status {sync_status = \"Unknown\"} == 1)"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 20 }, "content": "## Applications:" },
  {
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "targets": [
    { "expr": "argocd_app_sync_status==1" }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 29 }, "content": "## Server Stats:" },
  {
   "title": "Memory Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{job=\"argocd-server-metrics\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "GC Time Quantiles",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{job=\"argocd-server-metrics\", quantile=\"1\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{job=\"argocd-server-metrics\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 22, "x": 0, "y": 48 }, "content": "## grpc Services:" },
  {
   "title": "grpc service ApplicationService",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_server_handled_total{job=\"argocd-server-metrics\",grpc_service=\"application.ApplicationService\"} > 0",
     "legendFormat": "{{grpc_code}},{{grpc_method}}"
    }
   ]
  },
  {
   "title": "grpc service ClusterService",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_server_handled_total{job=\"argocd-server-metrics\",grpc_service=\"cluster.ClusterService\"} > 0",
     "legendFormat": "{{grpc_code}},{{grpc_method}}"
    }
   ]
  },
  {
   "title": "grpc service ProjectService",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_server_handled_total{job=\"argocd-server-metrics\",grpc_service=\"project.ProjectService\"} > 0",
     "legendFormat": "{{grpc_code}},{{grpc_method}}"
    }
   ]
  },
  {
   "title": "grpc service RepositoryService",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_server_handled_total{job=\"argocd-server-metrics\",grpc_service=\"repository.RepositoryService\"} > 0",
     "legendFormat": "{{grpc_code}},{{grpc_method}}"
    }
   ]
  },
  {
   "title": "grpc service SessionService",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_server_handled_total{job=\"argocd-server-metrics\",grpc_service=\"session.SessionService\"} > 0",
     "legendFormat": "{{grpc_code}},{{grpc_method}}"
    }
   ]
  },
  {
   "title": "grpc service VersionService",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_server_handled_total{job=\"argocd-server-metrics\",grpc_service=\"version.VersionService\"} > 0",
     "legendFormat": "{{grpc_code}},{{grpc_method}}"
    }
   ]
  },
  {
   "title": "grpc service AccountService",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_server_handled_total{job=\"argocd-server-metrics\",grpc_service=\"account.AccountService\"} >1",
     "legendFormat": "{{grpc_code}},{{grpc_method}}"
    }
   ]
  }
 ]
}